[workspace]
members = [
    "core"
]

[workspace.dependencies]
serde = { version = "1.0.159" }
tokio = { version = "1.27.0", features = ["fs", "macros"] }
regex = { version = "1.7.3" }
lazy_static = { version = "1.4.0" }
lazy-regex = { version = "2.5.0"}
anyhow = { version = "1.0.70" }