[workspace]
members = [
    "core"
]

[workspace.dependencies]
hashbrown = { version = "0.13.2", features = ["default", "serde"] }
serde = { version = "1.0.159" }
tokio = { version = "1.27.0", features = ["fs", "macros"] }
regex = { version = "1.7.3" }